-- Noma access tiers v4.
-- Run once in the Supabase SQL editor before deploying the matching Worker.
-- Safe to run again. Existing items and users are not deleted.

begin;

create table if not exists public.plans (
  code text primary key,
  display_name text not null,
  ai_scan_limit integer check (ai_scan_limit is null or ai_scan_limit >= 0),
  item_limit integer check (item_limit is null or item_limit >= 0),
  is_assignable boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.plans (code, display_name, ai_scan_limit, item_limit, is_assignable)
values
  ('free', 'Free', 3, 100, true),
  ('seed', 'Seed', 20, 1000, true),
  ('pro', 'Pro', null, 10000, false)
on conflict (code) do update
set display_name = excluded.display_name,
    ai_scan_limit = excluded.ai_scan_limit,
    item_limit = excluded.item_limit,
    is_assignable = excluded.is_assignable,
    updated_at = now();

create table if not exists public.seed_allowlist (
  email text primary key,
  active boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists seed_allowlist_email_lower_idx
  on public.seed_allowlist (lower(email));

create table if not exists public.user_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text not null default 'free' references public.plans(code),
  ai_scan_limit_override integer check (ai_scan_limit_override is null or ai_scan_limit_override >= 0),
  item_limit_override integer check (item_limit_override is null or item_limit_override >= 0),
  source text not null default 'signup',
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_credit_grants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null check (amount > 0),
  reason text not null default 'manual',
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists ai_credit_grants_user_active_idx
  on public.ai_credit_grants (user_id, expires_at);

create table if not exists public.ai_scan_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scan_id text not null,
  features text[] not null default '{}'::text[],
  feature_attempts jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, scan_id)
);

alter table public.ai_scan_usage
  add column if not exists feature_attempts jsonb not null default '{}'::jsonb;

create index if not exists ai_scan_usage_user_created_idx
  on public.ai_scan_usage (user_id, created_at desc);

alter table public.plans enable row level security;
alter table public.seed_allowlist enable row level security;
alter table public.user_entitlements enable row level security;
alter table public.ai_credit_grants enable row level security;
alter table public.ai_scan_usage enable row level security;

drop policy if exists "Authenticated users can read plans" on public.plans;
create policy "Authenticated users can read plans"
on public.plans for select to authenticated
using (true);

drop policy if exists "Users can read own entitlement" on public.user_entitlements;
create policy "Users can read own entitlement"
on public.user_entitlements for select to authenticated
using (auth.uid() = user_id);

revoke all on public.plans from anon;
revoke all on public.seed_allowlist from anon, authenticated;
revoke all on public.user_entitlements from anon;
revoke all on public.ai_credit_grants from anon, authenticated;
revoke all on public.ai_scan_usage from anon, authenticated;
grant select on public.plans to authenticated;
grant select on public.user_entitlements to authenticated;

create or replace function public.normalize_seed_allowlist_email()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.email := lower(trim(new.email));
  new.updated_at := now();
  if new.email = '' then
    raise exception 'Seed allowlist email cannot be empty';
  end if;
  return new;
end;
$$;

drop trigger if exists normalize_seed_allowlist_email_trigger on public.seed_allowlist;
create trigger normalize_seed_allowlist_email_trigger
before insert or update on public.seed_allowlist
for each row execute function public.normalize_seed_allowlist_email();

create or replace function public.ensure_noma_entitlement(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target_email text;
  is_seed boolean;
begin
  select lower(trim(u.email))
  into target_email
  from auth.users as u
  where u.id = target_user_id
    and u.email_confirmed_at is not null;

  if target_email is null then
    raise exception 'NOMA_AUTH_REQUIRED' using errcode = 'P0001';
  end if;

  select exists (
    select 1
    from public.seed_allowlist as allowlist
    where lower(allowlist.email) = target_email
      and allowlist.active
  )
  into is_seed;

  insert into public.user_entitlements (user_id, plan_code, source)
  values (target_user_id, case when is_seed then 'seed' else 'free' end, case when is_seed then 'allowlist' else 'signup' end)
  on conflict (user_id) do update
  set plan_code = case
        when is_seed and public.user_entitlements.plan_code = 'free' then 'seed'
        else public.user_entitlements.plan_code
      end,
      source = case
        when is_seed and public.user_entitlements.plan_code = 'free' then 'allowlist'
        else public.user_entitlements.source
      end,
      updated_at = case
        when is_seed and public.user_entitlements.plan_code = 'free' then now()
        else public.user_entitlements.updated_at
      end;
end;
$$;

revoke all on function public.ensure_noma_entitlement(uuid) from public;

create or replace function public.upgrade_seed_allowlist_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.active then
    insert into public.user_entitlements (user_id, plan_code, source)
    select u.id, 'seed', 'allowlist'
    from auth.users as u
    where lower(trim(u.email)) = lower(trim(new.email))
      and u.email_confirmed_at is not null
    on conflict (user_id) do update
    set plan_code = case
          when public.user_entitlements.plan_code = 'free' then 'seed'
          else public.user_entitlements.plan_code
        end,
        source = case
          when public.user_entitlements.plan_code = 'free' then 'allowlist'
          else public.user_entitlements.source
        end,
        updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists upgrade_seed_allowlist_user_trigger on public.seed_allowlist;
create trigger upgrade_seed_allowlist_user_trigger
after insert or update of active, email on public.seed_allowlist
for each row execute function public.upgrade_seed_allowlist_user();

insert into public.user_entitlements (user_id, plan_code, source)
select
  u.id,
  case when exists (
    select 1
    from public.seed_allowlist as allowlist
    where lower(allowlist.email) = lower(trim(u.email))
      and allowlist.active
  ) then 'seed' else 'free' end,
  case when exists (
    select 1
    from public.seed_allowlist as allowlist
    where lower(allowlist.email) = lower(trim(u.email))
      and allowlist.active
  ) then 'allowlist' else 'signup' end
from auth.users as u
where u.email_confirmed_at is not null
on conflict (user_id) do nothing;

create or replace function public.get_my_access()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_user_id uuid := auth.uid();
  entitlement public.user_entitlements%rowtype;
  plan_row public.plans%rowtype;
  base_ai_limit integer;
  effective_ai_limit integer;
  effective_item_limit integer;
  bonus_credits integer;
  ai_used integer;
  item_count integer;
begin
  if current_user_id is null then
    raise exception 'NOMA_AUTH_REQUIRED' using errcode = 'P0001';
  end if;

  perform public.ensure_noma_entitlement(current_user_id);

  select * into entitlement
  from public.user_entitlements
  where user_id = current_user_id;

  select * into plan_row
  from public.plans
  where code = entitlement.plan_code;

  base_ai_limit := coalesce(entitlement.ai_scan_limit_override, plan_row.ai_scan_limit);
  effective_item_limit := coalesce(entitlement.item_limit_override, plan_row.item_limit);

  select coalesce(sum(grant_row.amount), 0)::integer
  into bonus_credits
  from public.ai_credit_grants as grant_row
  where grant_row.user_id = current_user_id
    and (grant_row.expires_at is null or grant_row.expires_at > now());

  effective_ai_limit := case
    when base_ai_limit is null then null
    else base_ai_limit + bonus_credits
  end;

  select count(*)::integer into ai_used
  from public.ai_scan_usage
  where user_id = current_user_id;

  select count(*)::integer into item_count
  from public.items
  where user_id::text = current_user_id::text;

  return jsonb_build_object(
    'planCode', entitlement.plan_code,
    'planName', plan_row.display_name,
    'aiScanLimit', effective_ai_limit,
    'aiScansUsed', ai_used,
    'aiScansRemaining', case when effective_ai_limit is null then null else greatest(effective_ai_limit - ai_used, 0) end,
    'itemLimit', effective_item_limit,
    'itemCount', item_count,
    'itemsRemaining', case when effective_item_limit is null then null else greatest(effective_item_limit - item_count, 0) end
  );
end;
$$;

revoke all on function public.get_my_access() from public;
grant execute on function public.get_my_access() to authenticated;

create or replace function public.authorize_ai_scan(p_scan_id text, p_feature text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_user_id uuid := auth.uid();
  entitlement public.user_entitlements%rowtype;
  plan_row public.plans%rowtype;
  usage_row public.ai_scan_usage%rowtype;
  base_ai_limit integer;
  effective_ai_limit integer;
  bonus_credits integer;
  ai_used integer;
  feature_attempt_count integer;
begin
  if current_user_id is null then
    raise exception 'NOMA_AUTH_REQUIRED' using errcode = 'P0001';
  end if;
  if p_scan_id is null or p_scan_id !~ '^[A-Za-z0-9:_-]{8,120}$' then
    raise exception 'NOMA_INVALID_SCAN_ID' using errcode = 'P0001';
  end if;
  if p_feature not in ('vision', 'matting') then
    raise exception 'NOMA_INVALID_AI_FEATURE' using errcode = 'P0001';
  end if;

  perform public.ensure_noma_entitlement(current_user_id);
  perform pg_advisory_xact_lock(hashtextextended(current_user_id::text, 0));

  select * into entitlement
  from public.user_entitlements
  where user_id = current_user_id
  for update;

  select * into plan_row
  from public.plans
  where code = entitlement.plan_code;

  base_ai_limit := coalesce(entitlement.ai_scan_limit_override, plan_row.ai_scan_limit);

  select coalesce(sum(grant_row.amount), 0)::integer
  into bonus_credits
  from public.ai_credit_grants as grant_row
  where grant_row.user_id = current_user_id
    and (grant_row.expires_at is null or grant_row.expires_at > now());

  effective_ai_limit := case
    when base_ai_limit is null then null
    else base_ai_limit + bonus_credits
  end;

  select * into usage_row
  from public.ai_scan_usage
  where user_id = current_user_id
    and scan_id = p_scan_id;

  if found then
    feature_attempt_count := coalesce((usage_row.feature_attempts ->> p_feature)::integer, 0);
    if feature_attempt_count >= 2 then
      select count(*)::integer into ai_used
      from public.ai_scan_usage
      where user_id = current_user_id;

      return jsonb_build_object(
        'allowed', false,
        'charged', false,
        'reason', 'retry_limit',
        'planCode', entitlement.plan_code,
        'limit', effective_ai_limit,
        'used', ai_used,
        'remaining', case when effective_ai_limit is null then null else greatest(effective_ai_limit - ai_used, 0) end
      );
    end if;

    update public.ai_scan_usage
    set features = case
          when p_feature = any(features) then features
          else array_append(features, p_feature)
        end,
        feature_attempts = jsonb_set(
          feature_attempts,
          array[p_feature],
          to_jsonb(feature_attempt_count + 1),
          true
        ),
        updated_at = now()
    where id = usage_row.id;

    select count(*)::integer into ai_used
    from public.ai_scan_usage
    where user_id = current_user_id;

    return jsonb_build_object(
      'allowed', true,
      'charged', false,
      'planCode', entitlement.plan_code,
      'limit', effective_ai_limit,
      'used', ai_used,
      'remaining', case when effective_ai_limit is null then null else greatest(effective_ai_limit - ai_used, 0) end
    );
  end if;

  select count(*)::integer into ai_used
  from public.ai_scan_usage
  where user_id = current_user_id;

  if effective_ai_limit is not null and ai_used >= effective_ai_limit then
    return jsonb_build_object(
      'allowed', false,
      'charged', false,
      'reason', 'quota_exhausted',
      'planCode', entitlement.plan_code,
      'limit', effective_ai_limit,
      'used', ai_used,
      'remaining', 0
    );
  end if;

  insert into public.ai_scan_usage (user_id, scan_id, features, feature_attempts)
  values (current_user_id, p_scan_id, array[p_feature], jsonb_build_object(p_feature, 1));

  ai_used := ai_used + 1;
  return jsonb_build_object(
    'allowed', true,
    'charged', true,
    'planCode', entitlement.plan_code,
    'limit', effective_ai_limit,
    'used', ai_used,
    'remaining', case when effective_ai_limit is null then null else greatest(effective_ai_limit - ai_used, 0) end
  );
end;
$$;

revoke all on function public.authorize_ai_scan(text, text) from public;
grant execute on function public.authorize_ai_scan(text, text) to authenticated;

create or replace function public.enforce_noma_item_limit()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target_user_id uuid := (new.user_id::text)::uuid;
  effective_item_limit integer;
  current_item_count integer;
begin
  if exists (
    select 1
    from public.items as existing_item
    where existing_item.id::text = new.id::text
      and existing_item.user_id::text = new.user_id::text
  ) then
    return new;
  end if;

  perform public.ensure_noma_entitlement(target_user_id);
  perform pg_advisory_xact_lock(hashtextextended(target_user_id::text, 1));

  select coalesce(entitlement.item_limit_override, plan_row.item_limit)
  into effective_item_limit
  from public.user_entitlements as entitlement
  join public.plans as plan_row on plan_row.code = entitlement.plan_code
  where entitlement.user_id = target_user_id;

  if effective_item_limit is null then
    return new;
  end if;

  select count(*)::integer into current_item_count
  from public.items
  where user_id::text = target_user_id::text;

  if current_item_count >= effective_item_limit then
    raise exception 'NOMA_ITEM_LIMIT_REACHED:%', effective_item_limit using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_noma_item_limit_trigger on public.items;
create trigger enforce_noma_item_limit_trigger
before insert on public.items
for each row execute function public.enforce_noma_item_limit();

notify pgrst, 'reload schema';
commit;

-- Verification. New projects normally show an empty allowlist.
select code, display_name, ai_scan_limit, item_limit, is_assignable
from public.plans
order by case code when 'free' then 1 when 'seed' then 2 else 3 end;
